Solve sum & Counter btn
js-tasks-ru/vue-20230516_annlisandias pull request #1
Opened 2023-05-08 16:36 UTC by Hanna-hanna

2023-05-08 16:36 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @ShGKme должен запустить тесты.

2023-05-23 15:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-23 19:14 UTC, ShGKme reviewed
По старым задачам всё хорошо (не проверял до начала курса).
Но есть новые добавленные в PR задачи.

2023-05-26 20:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-13 22:16 UTC, ShGKme requested changes
В `01-basics/03-MarkedList` требуется сделать такое вычисляемое свойство, которое помогает сразу выводить маркированный список.

2023-06-13 22:16 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +    },
На вебинаре мы использовали вычисляемое свойство для подготовки **отфильтрованных** данных и дальнейшего вывода отфильтрованного списка. Но здесь - другая задача. Здесь требуется вывести **ВСЕ** данные, но некоторые элементы - **отметить** маркировкой.

В вычисляемом свойстве нужно вернуть что-то, что поможет вывести список с не только самой почтой, но и классом с маркировкой при необходимости.

Для этого можно на основе исходного массива строк с почтами вернуть новый массив, где каждый элемент - объект. В объект уже можно положить как исходную почту, так и флаг о маркировке (вычислять также, как сейчас делаете проверку в фильтре). Альтернативное решение - вычислить что-то дополнительное, что позволит быстро по почте при выводе узнать, нужно ли её маркировать.

2023-06-13 22:16 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +      </ul>
В текущем решении для вывода списка идёт перебор всех почт, а также заранее вычисляется отфильтрованный список. При вычислении отфильтрованного списка уже для каждой почты проверяется, подходит она, или нет. Затем при выводе для каждой почты происходит ещё один перебор уже отфильтрованного списка, чтобы проверить, не попадает ли почта в список ранее вычисленного отфильтрованного (где её уже проверили). И так при каждом рендеринге, даже если новый рендеринг не был связан с изменением поиска или списка почт. В итоге вычисляемое свойство не помогает выводить почты, а напротив даже усложняет и замедляет работу.

2023-06-13 22:16 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +      </ul>
Также напомню, что использование методов в шаблоне в целом чаще плохая практика, если это не метод форматирования вывода или небольшая утилита, а метод с логикой работы с данными.

2023-06-13 22:16 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +  },
Для использования функции в компоненте её не требуется переносить в методы. В методах компонента должны быть те функции, которые являются частью компонента. Изменяют или используют его свойства, обрабатывают события внутри компонента. Могут в методах также быть и простые функции, если они используются только в других методах этого же компонента и не нужны вне компонента.

Здесь же `fetchMeetupById` - самостоятельная функция.

Самостоятельную функцию могут использовать другие компоненты, функции и прочие модули приложения вне разрабатываемого компонента.

2023-07-03 19:09 UTC, ShGKme reviewed
Обновления приняты, но в PR есть новые добавленные задачи

2023-07-04 06:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-26 05:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-26 05:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-27 22:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-28 17:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-28 17:35 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-07-28 17:37 UTC, merged